ALTER TABLE profiles ADD COLUMN IF NOT EXISTS cep TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS uf TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS cidade TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS logradouro TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS bairro TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS numero TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS complemento TEXT;
